suppressMessages(devtools::load_all(".", quiet = TRUE))
con <- entropia_connect("data-test/entropia.sqlite", quiet = TRUE)
on.exit(entropia_disconnect(con), add = TRUE)
cat("schema_version:", attr(con, "schema_version"), "\n")
v <- entropia_validate(con)
cat("validate findings:", nrow(v), "\n")
if (nrow(v) > 0) print(v)
cat("row_counts head:\n")
print(utils::head(attr(v, "row_counts"), 8))
cat("\nstatus:\n")
st <- entropia_status(con)
print(st)
