pkgload::load_all("G:/EntropIA-Stack/EntropIA-R", quiet = TRUE)
con <- entropiaR::entropia_connect("G:/EntropIA-Stack/EntropIA-R/scratch/ref-copy.sqlite")
on.exit(try(entropia_disconnect(con), silent = TRUE))
cat("schema version:", entropia_schema_version(con), "\n")
items <- entropia_collect(entropia_items(con))
cat("items collected:", nrow(items), "\n")
prof <- entropia_temporal_profile(items, created_at, unit = "month")
cat("temporal profile by month:\n")
print(prof)
cat("temporal profile by year (top 5):\n")
print(utils::head(entropia_temporal_profile(items, created_at, unit = "year"), 5))
# document lengths on real corpus text (first 50 assets with text)
txt <- dplyr::collect(entropia_text(con, assets = NULL))
lens <- entropia_document_lengths(txt)
cat("document_lengths on real text layer:", nrow(lens), "rows,", sum(!is.na(lens$n_words)), "with text\n")
print(utils::head(lens[lens$type == "pdf" & !is.na(lens$n_words), c("id", "type", "n_chars", "n_words")], 3))
