Sys.setenv(RSTUDIO_PANDOC = "C:/Program Files/RStudio/resources/app/bin/quarto/bin/tools")
lib <- file.path(tempdir(), "simlib2")
dir.create(lib, recursive = TRUE, showWarnings = FALSE)
.libPaths(c(lib, .libPaths()))
pkg <- devtools::build("G:/EntropIA-Stack/EntropIA-R", quiet = TRUE)
utils::install.packages(pkg, lib = lib, repos = NULL, type = "source", quiet = TRUE)
library(entropiaR)
h <- utils::help("entropiaR-package", package = "entropiaR")
rd <- utils:::.getHelpFile(h)
txt <- paste(capture.output(tools::Rd2txt(rd)), collapse = "\n")
cat("=== Rd2txt package doc (first 1200 chars) ===\n")
cat(substr(txt, 1, 1200), "\n")
cat("=== greps ===\n")
cat("deprecate_warn:", grepl("deprecate_warn", txt, fixed = TRUE), "\n")
cat("lifecycle lower:", grepl("lifecycle", txt, fixed = TRUE), "\n")
cat("Lifecycle upper:", grepl("Lifecycle", txt, fixed = TRUE), "\n")
cat("experimental:", grepl("experimental", txt, fixed = TRUE), "\n")
