sink("scratch/fulltest_smoke.log")
pkgload::load_all("G:/EntropIA-Stack/EntropIA-R", quiet = TRUE)
cat("loaded:", as.character(utils::packageVersion("entropiaR")), "\n")
con <- entropia_connect(system.file("extdata", "entropia-example.sqlite", package = "entropiaR"))
cat("schema:", entropia_schema_version(con), "\n")
items <- entropia_collect(entropia_items(con))
cat("items rows:", nrow(items), "created_at class:", class(items$created_at), "\n")
entropia_disconnect(con)
cat("SMOKE OK\n")
sink()
