sink("G:/EntropIA-Stack/EntropIA-R/scratch/probe2.log")
cat("start\n"); flush.console()
cat("rlang:", requireNamespace("rlang", quietly = TRUE), "\n")
cat("lifecycle:", requireNamespace("lifecycle", quietly = TRUE), "\n")
cat("loading rlang\n"); library(rlang)
cat("cnd_signal test\n")
cnd <- structure(class = c("my_error", "error", "condition"), list(message = "boom", call = NULL))
res <- tryCatch({ rlang::cnd_signal(cnd); "no-error" }, error = function(e) class(e))
cat("class:", paste(res, collapse = ","), "\n")
msg <- tryCatch(rlang::cnd_signal(cnd), error = function(e) conditionMessage(e))
cat("msg:", msg, "\n")
b <- lifecycle::badge("experimental")
cat("badge:", substr(b, 1, 300), "\n")
cat("done\n")
sink()
